@api = http://localhost:8080/api/users


### Creating user

# @name create
POST {{api}}/
Content-Type: application/json

{
    "name": "lorenaAEri",
    "age": 35,
    "email": "losri@hotmail.com",
    "password": "123456",
    "role":"user"
}

### 
@authToken = {{create.response.headers.X-AuthToken}}

# @name Update
PATCH {{api}}/649e01e72a11b04b5864df95
Authorization: {{authToken}}
Content-Type: application/json

{
    "name": "lorenaAEri",
    "age": 35,
    "email": "lor@hotmail.com",
    "password": "123456",
    "role":"user"
}


### Get users

# @name GetUser
GET {{api}}/649e01e72a11b04b5864df95
Authorization: {{authToken}}
Content-Type: application/json

{
    "name": "lorenaAEri",
    "age": 35,
    "email": "lor@hotmail.com",
    "password": "123456",
    "role":"user"
}


### Delete user

# @name DeleteUser
DELETE {{api}}/649e2fd0efa948379b789dbb
Authorization: {{authToken}}
Content-Type: application/json

{
    "name": "lorenaAEri",
    "age": 35,
    "email": "lor@hotmail.com",
    "password": "123456",
    "role":"user"
}

